name: FastAPI ML Deployment

on:
  push:
    branches:
      - main  # or whatever your branch is
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install gdown

    - name: Download checkpoint folder from Google Drive
      run: |
        gdown --folder https://drive.google.com/drive/folders/1_g6NKcUfkpUOKgbq1vBio1Pm5DmIeHAA
        

    - name: Run Tests or Start FastAPI
      run: |
        # Example: you can run tests here if you have any
        # pytest tests/

        # Or just start FastAPI app for testing purpose
        uvicorn main:app --host 0.0.0.0 --port 8000 --reload
